### PR TITLE
fix(#118): Check CGroupsV2 files when calculating max/init memory (ba…

### PR DESCRIPTION
**Pull request by grgrzybek**
…sed on #113)

### CODE REVIEW

**Comment by grgrzybek** [comment]
cc: @rhuss @matmannion

**Comment by rhuss** [comment]
@grgrzybek what is the difference to the original PR ?

It looks like that the CircleCI has issues currently .... 🤔

**Comment by grgrzybek** [comment]
#113 didn't check potential subgroups. In theory, containers namespace the fs, so subgroups are visible under `/`, but who knows...

`cat /proc/self/cgroup` shows just `0::/` under OpenShift, but locally it returns something like `0::/user.slice/user-22693.slice/user@22693.service/app.slice/vte-spawn-732802a7-5cc4-43c0-bf5a-29e71bd2e7d7.scope`.

**Comment by rhuss** [comment]
still not sure why circle jobs don't work, so it might be better to move to Github Actions anyways. But the PR is sound to me, so let's merge it.

Please note, that I can't support this project anymore timewise (and I'm not 100% convinced that it really is needed these days, the benefits are not so huge anymore), but I'm still supportive to integrate PRs (well, pressing the button :)

**Comment by rhuss** [comment]
@grgrzybek I am not sure if this is possible, but there is a test suite in which you might want to add a test case for this addition, too (though I am not sure how to simulate CGroupsV2 ...)

**Comment by grgrzybek** [comment]
@rhuss isn't the test suite part of some docker image? I didn't find shell tests here in this repo...

**Comment by rhuss** [comment]
@grgrzybek the tests are defined in `test/t` (they are leveraging `bats` as Shell test framework), and you are right, they are packaged as Docker images before execution

**Comment by grgrzybek** [comment]
oh my - I should've looked into `test` directory ;)
I'll check what I can do. I _may_ update the tests, but I'm not sure if I can do anything about CircleCI configuration:
```
Load key "/root/.ssh/id_rsa": invalid format
Permission denied (publickey).
```

**Comment by rhuss** [comment]
yeah, I'm also not sure about why CircleCI has this issue. I'm off next week for Kubecon, but I can look into it the overnext week to move to GitHub actions (shouldn't be hard). If I don't forget it :)

**Pull request merged**
